apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: graph-kb
resources:
  - namespace.yaml
  - sealedsecret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - networkpolicy.yaml
  - resourcequota.yaml
