apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: graph-kb-secrets
  namespace: graph-kb
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    anthropic-api-key: REPLACEME
    backstage-url: REPLACEME
    backstage-token: REPLACEME
    graph-kb-token: AgAJQbQx0LbQaqXSa8qaHRXSsUcTVRYLGYS6Q9hLztud1NnJni66/i6UPIpbGpXpw+DzDnEIbKYOCZgn7fdXH/gElqD+XqucPApINrpmw7PJoBSmCH1YDP1ttzrd2WJJiaRrtJbEIAdiPZFGbriBN9USX+vJdxb808vwbrpl+X2iv7JK1CLTqVwJ25UUdCbC1uZvanIMWo/P4Toke9ZkVVXmhr+6+mesJGXt0yVqlIgZLzck5SZLeCsRI8yHozl/XyLPORn8UmiCqr2lqEEnNEznQwUYfrcWO6KPoqWdsMLB7wUkLfauEQ5uqbFyoNJxcRaYGhyY1orbLBiMlm+9Vd+mXbnPLKI18a9F+lmK01SbE2drod7QCqDwVZDhZ0bvr+XvH9N53YQkJIL/tbb8ciVG57sgFSWt+ry0fCTxegZX+5DDrVH74hY61TRv9U4gDXc2z4dgInyFV1iVUGaSBRp3AUXjInv1iCHu2t+3d+ka4ZSckDMz7es5cRv+45XC/TlJgkB4+woruWBlydn4tNwjUKaQ/bScFG0VJU/I/xk8d1AvBnm9DaBSrgFqaRuQwswO1jOrPJorVGYIm5KLDfkjzIM5kWMH6E32mPJUOouHUNRaqaGS6PFEh6k7Ks/fj0e9EtgRoFJXdH8NyhsbTf/e/t8CZSZIvxXlVnlNa7Hs7W8doStf4r0xmzGXDiIqoKQK5Zv5kJla9TIHvK+iIC4djIAncRFfvMp42KKTfSM4AGSLzYc6dYvAisEVVgnpXrz0m8vdYYU1K3u/u/XcKSvZ
  template:
    metadata:
      name: graph-kb-secrets
      namespace: graph-kb
    type: Opaque
