apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: graph-kb-secrets
  namespace: graph-kb
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    anthropic-api-key: REPLACEME
    backstage-url: REPLACEME
    backstage-token: REPLACEME
    graph-kb-token: REPLACEME
  template:
    metadata:
      name: graph-kb-secrets
      namespace: graph-kb
    type: Opaque
